language: php

sudo: false

php:
  - 7.0
  - 7.0snapshot
  - 7.1
  - 7.1snapshot
  - master

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-progress --no-suggest --ansi"

before_install:
  - composer self-update
  - composer clear-cache
  - composer update

script: ./vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  on_success: never
  on_failure: always
