language: php

sudo: false

php:
  - 7.0

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--ansi --no-interaction --no-progress --no-suggest"

before_install:
  - composer self-update
  - composer clear-cache
  - composer update

script: ./vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  on_success: never
  on_failure: always
