language: php

sudo: false

php:
  - 7.0
  - 7.0snapshot
  - 7.1
  - 7.1snapshot
  - master

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
  - composer self-update
  - composer clear-cache

script: phpunit

before_script:
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  on_success: never
  on_failure: always
